name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for create a new issue, your contributions is appreciated, happy coding!"
        pr-message: "Thank you for create a new pull requests, your contributions is appreciated, happy coding"
